// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrivateExpenses.Infrastructure.Persistence;

#nullable disable

namespace PrivateExpenses.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PrivateExpensesDbContext))]
    [Migration("20260807184209_ValueGeneratedNeverForClientKeys")]
    partial class ValueGeneratedNeverForClientKeys
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("PrivateExpenses.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("IconKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("PrivateExpenses.Domain.Entities.Expense", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("ExpenseDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MerchantName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<long>("TotalCents")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ExpenseDate");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("MerchantName");

                    b.ToTable("Expenses", (string)null);
                });

            modelBuilder.Entity("PrivateExpenses.Domain.Entities.ExpenseItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ExpenseId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeposit")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDiscount")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(10, 3)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalCents")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("UnitPriceCents")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExpenseId");

                    b.ToTable("ExpenseItems", (string)null);
                });

            modelBuilder.Entity("PrivateExpenses.Domain.Entities.ExpenseItemShare", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("AmountCents")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ExpenseItemId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.HasIndex("ExpenseItemId", "PersonId")
                        .IsUnique();

                    b.ToTable("ExpenseItemShares", (string)null);
                });

            modelBuilder.Entity("PrivateExpenses.Domain.Entities.ExpensePayment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("AmountCents")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ExpenseId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.HasIndex("ExpenseId", "PersonId")
                        .IsUnique();

                    b.ToTable("ExpensePayments", (string)null);
                });

            modelBuilder.Entity("PrivateExpenses.Domain.Entities.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ColorKey")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Initial")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("People", (string)null);
                });

            modelBuilder.Entity("PrivateExpenses.Domain.Entities.ReceiptDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ExpenseId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<string>("ParsingError")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ParsingProvider")
                        .HasColumnType("TEXT");

                    b.Property<int>("ParsingStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RawStructuredResult")
                        .HasColumnType("TEXT");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExpenseId");

                    b.HasIndex("FileHash");

                    b.HasIndex("StoredFileName")
                        .IsUnique();

                    b.ToTable("ReceiptDocuments", (string)null);
                });

            modelBuilder.Entity("PrivateExpenses.Domain.Entities.Settlement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("AmountCents")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FromPersonId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("SettlementDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ToPersonId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FromPersonId");

                    b.HasIndex("SettlementDate");

                    b.HasIndex("ToPersonId");

                    b.ToTable("Settlements", (string)null);
                });

            modelBuilder.Entity("PrivateExpenses.Domain.Entities.Expense", b =>
                {
                    b.HasOne("PrivateExpenses.Domain.Entities.Category", "Category")
                        .WithMany("Expenses")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("PrivateExpenses.Domain.Entities.ExpenseItem", b =>
                {
                    b.HasOne("PrivateExpenses.Domain.Entities.Expense", "Expense")
                        .WithMany("Items")
                        .HasForeignKey("ExpenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Expense");
                });

            modelBuilder.Entity("PrivateExpenses.Domain.Entities.ExpenseItemShare", b =>
                {
                    b.HasOne("PrivateExpenses.Domain.Entities.ExpenseItem", "ExpenseItem")
                        .WithMany("Shares")
                        .HasForeignKey("ExpenseItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrivateExpenses.Domain.Entities.Person", "Person")
                        .WithMany("ExpenseItemShares")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ExpenseItem");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("PrivateExpenses.Domain.Entities.ExpensePayment", b =>
                {
                    b.HasOne("PrivateExpenses.Domain.Entities.Expense", "Expense")
                        .WithMany("Payments")
                        .HasForeignKey("ExpenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrivateExpenses.Domain.Entities.Person", "Person")
                        .WithMany("ExpensePayments")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Expense");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("PrivateExpenses.Domain.Entities.ReceiptDocument", b =>
                {
                    b.HasOne("PrivateExpenses.Domain.Entities.Expense", "Expense")
                        .WithMany("Documents")
                        .HasForeignKey("ExpenseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Expense");
                });

            modelBuilder.Entity("PrivateExpenses.Domain.Entities.Settlement", b =>
                {
                    b.HasOne("PrivateExpenses.Domain.Entities.Person", "FromPerson")
                        .WithMany()
                        .HasForeignKey("FromPersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PrivateExpenses.Domain.Entities.Person", "ToPerson")
                        .WithMany()
                        .HasForeignKey("ToPersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromPerson");

                    b.Navigation("ToPerson");
                });

            modelBuilder.Entity("PrivateExpenses.Domain.Entities.Category", b =>
                {
                    b.Navigation("Expenses");
                });

            modelBuilder.Entity("PrivateExpenses.Domain.Entities.Expense", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Items");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("PrivateExpenses.Domain.Entities.ExpenseItem", b =>
                {
                    b.Navigation("Shares");
                });

            modelBuilder.Entity("PrivateExpenses.Domain.Entities.Person", b =>
                {
                    b.Navigation("ExpenseItemShares");

                    b.Navigation("ExpensePayments");
                });
#pragma warning restore 612, 618
        }
    }
}
